### ISSUE TITLE
Cannot move window so part of it is off screen. 

### ISSUE THREAD

**Issue by BensonBear** [ickyicky/window-calls#6]
In particular, I need to move a window so that its top is off the top of the screen (so y = - 50 for example).  

It is definitely possible to position window like that, it can be done with alt-f7

I can kludge it up with alt-f7 and ydotool but this would be far cleaner. 
 
I will look at code myself if you are not interested in adding (or, I would say, fixing, this). 

Also, it seems "move" on its own does not work at all  ("win.meta_window is undefined")

**Comment by BensonBear** [comment]
> I will look at code myself if you are not interested in adding

Okay, I changed it, if you want to change it you can to, otherwise I will just keep my own copy.

I don't know gnome shell programming yet, but easy to guess at it: 

-  changed the "u" type on the x,y inputs to "i" so they can be negative,
-  changed the boolean in the move and resize calls to true so that the window is allowed to move off the screen.   -  moved the "meta_window" field selector in Move function down to the correct place
-  added -- on the dbus command line before the input args so that negative args can be parsed 

works okay for me like that.   Some might not like the ability to move a window partly of screen but thing it really should be possible.

**Comment by ickyicky** [comment]
Specyfing window by title or class in not the best idea, since you can have multiple windows of same class or same title. I was thinking about making "Search" call which would basically filter through List results by given parameters such as title or class ;) Maybe in near future i will add it.

As for the error, its my bad, last version of extension was poorly tested by me as it was done during my vacations, I fixed Move to Your suggestions, as I do agree that moving off the screen should be allowed. The newest version on gnome-extensions is fully functional in that regard.

**Comment by BensonBear** [comment]
> Specyfing window by title or class in not the best idea, since you can have multiple windows of same class or same title.

Yes, it cannot be the default operation, but it is very convenient in my case since the bulk of my windows are quite identifiable by title or class (so I can have key bindings to deal with the editor, the file manager, and multiple win-apps inside firefox with their own window, etc., all natural specified in user terms).   In fact I have have to use this program first to extract the window id with a bunch of shell rigamarole, and then stuff it back in to another call.  
 
But, it's no big deal of course.

**Comment by ickyicky** [comment]
In the newest version argument type was changed to "i" instead of "u", so the issue no longer exists
